export const abiGasPriceRenderer = [
  { inputs: [], name: "AmountTooLarge", type: "error" },
  {
    inputs: [
      { internalType: "uint256", name: "tokenId", type: "uint256" },
      {
        components: [
          { internalType: "string", name: "name", type: "string" },
          { internalType: "string", name: "description", type: "string" },
          { internalType: "address[]", name: "artifact", type: "address[]" },
          { internalType: "uint32", name: "renderer", type: "uint32" },
          { internalType: "uint32", name: "mintedBlock", type: "uint32" },
          { internalType: "uint64", name: "closeAt", type: "uint64" },
          { internalType: "uint128", name: "data", type: "uint128" },
        ],
        internalType: "struct Token",
        name: "token",
        type: "tuple",
      },
    ],
    name: "animationURI",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "tokenId", type: "uint256" },
      {
        components: [
          { internalType: "string", name: "name", type: "string" },
          { internalType: "string", name: "description", type: "string" },
          { internalType: "address[]", name: "artifact", type: "address[]" },
          { internalType: "uint32", name: "renderer", type: "uint32" },
          { internalType: "uint32", name: "mintedBlock", type: "uint32" },
          { internalType: "uint64", name: "closeAt", type: "uint64" },
          { internalType: "uint128", name: "data", type: "uint128" },
        ],
        internalType: "struct Token",
        name: "token",
        type: "tuple",
      },
    ],
    name: "generateSVG",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "tokenId", type: "uint256" },
      {
        components: [
          { internalType: "string", name: "name", type: "string" },
          { internalType: "string", name: "description", type: "string" },
          { internalType: "address[]", name: "artifact", type: "address[]" },
          { internalType: "uint32", name: "renderer", type: "uint32" },
          { internalType: "uint32", name: "mintedBlock", type: "uint32" },
          { internalType: "uint64", name: "closeAt", type: "uint64" },
          { internalType: "uint128", name: "data", type: "uint128" },
        ],
        internalType: "struct Token",
        name: "token",
        type: "tuple",
      },
    ],
    name: "imageURI",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "name",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "tokenId", type: "uint256" },
      {
        components: [
          { internalType: "string", name: "name", type: "string" },
          { internalType: "string", name: "description", type: "string" },
          { internalType: "address[]", name: "artifact", type: "address[]" },
          { internalType: "uint32", name: "renderer", type: "uint32" },
          { internalType: "uint32", name: "mintedBlock", type: "uint32" },
          { internalType: "uint64", name: "closeAt", type: "uint64" },
          { internalType: "uint128", name: "data", type: "uint128" },
        ],
        internalType: "struct Token",
        name: "token",
        type: "tuple",
      },
    ],
    name: "uri",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "version",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "pure",
    type: "function",
  },
];
