export const abiMintBounty = [
  {
    inputs: [{ name: "tokenContract", type: "address" }],
    name: "isBountyClaimable",
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "tokenContract", type: "address" }],
    name: "claimBounty",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "tokenContract", type: "address" },
      { name: "recipient", type: "address" },
      { name: "artifactsToMint", type: "uint256" },
      { name: "minterReward", type: "uint256" },
      { name: "maxArtifactPrice", type: "uint256" },
    ],
    name: "createBounty",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { name: "tokenContract", type: "address" },
      { name: "recipient", type: "address" },
      { name: "paused", type: "bool" },
      { name: "artifactsToMint", type: "uint256" },
      { name: "minterReward", type: "uint256" },
      { name: "maxArtifactPrice", type: "uint256" },
    ],
    name: "updateBounty",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "tokenContract", type: "address" }],
    name: "fundBounty",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { name: "tokenContract", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    name: "withdrawBalance",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "tokenContract", type: "address" },
      { name: "tokenIds", type: "uint256[]" },
      { name: "recipient", type: "address" },
    ],
    name: "withdrawArtifacts",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "", type: "address" }],
    name: "bounties",
    outputs: [
      { name: "recipient", type: "address" },
      { name: "paused", type: "bool" },
      { name: "lastMintedId", type: "uint96" },
      { name: "artifactsToMint", type: "uint256" },
      { name: "minterReward", type: "uint256" },
      { name: "maxArtifactPrice", type: "uint256" },
      { name: "balance", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
] as const;